### ISSUE TITLE
Modified SerialGenerator + migrations

### ISSUE THREAD

**Issue by DestinyMKas** [fwolfsjaeger/doctrine-cockroachdb#7]
Hello,

I use modified SerialGenerator which is provided as recommended way to generate PRIMARY KEYS.

Entity:
```php
#[ORM\Id]
#[ORM\GeneratedValue(strategy: 'CUSTOM')]
#[ORM\CustomIdGenerator(class: SerialGenerator::class)]
#[ORM\Column(name: 'id', type: Types::BIGINT, options: ['unsigned' => true])]
public ?int $id = null;
```

services.yml
```yaml
    DoctrineCockroachDB\ORM\Listener\AddDefaultToSerialGeneratorListener:
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    DoctrineCockroachDB\ORM\Listener\RemoveDefaultFromForeignKeysListener:
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
```

The issue, that migration always generates unnecessary changes:

```php
<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250521114216 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE address ALTER id SET DEFAULT unique_rowid()
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE address ALTER id DROP IDENTITY
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE address ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE address ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
    }
}
```

If I try to execute this migration, I get an error:
```
SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  column "id" of relation "address" is not an identity column
```

Cockroach db v25.1.5
fwolfsjaeger/doctrine-cockroachdb-bundle v0.9.2
doctrine/dbal v4.2.3
doctrine/doctrine-migrations-bundle v3.4.2

Any suggestions how to solve this issue?
